version: "3.9"

services:
  portainer:
    image: "cr.portainer.io/portainer/portainer-ce:2.9.3"
    container_name: portainer
    environment:
      - VIRTUAL_HOST=${DOCKER-DOMAIN}
      - VIRTUAL_PORT=9000
    env_file:
      - ./.env
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - docker-net
networks:
  docker-net:
    external: ${NET_EXTERNAL}

volumes:
  portainer_data:
    external: ${VOLUME_EXTERNAL}